### ISSUE TITLE
Question / possible bug?

### ISSUE THREAD

**Issue by architelos** [12944qwerty/TagScript-Blocks#1]
![image](https://user-images.githubusercontent.com/108888162/232315675-b646b8df-c765-46f5-9ca4-69867a0b334a.png)
Would this be invalid? I see no reason it would. but the tagscript code area isn't being updated.

**Comment by 12944qwerty** [comment]
I must've missed the if block. Something must be broken about it that I didn't catch, I'll fix it soon. Thanks!
